name: Web-App-Analyzer CI/CD

on:
  push:
    branches:
      - develop


jobs:
  deploy:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Go Lang
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test -v ./internal/controller/... ./internal/service/...

      - name: Run Unit Tests with coverage
        run: go test -cover ./internal/controller/... ./internal/service/...